name: Deploy Frontend

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Получаем актуальный код
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          clean: true

      # 2. Заходим в рабочую директорию и запускаем docker compose
      - name: Build and deploy
        run: sudo docker compose up -d --build || exit 1
        working-directory: ${{ github.workspace }}