name: Test React App
on: push
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Get repository
      uses: actions/checkout@v3
    - name: Intall dependencies
      run: npm ci
    - name: Test App
      run: npm run test